### ISSUE TITLE
 ClientConn.Connect error: unsupported minor version, less than 8: 0

### ISSUE THREAD

**Issue by toozande** [amitbet/vncproxy#14]
hello
when i run on windows 10 with vnc server 6.5.0 I get this error
 ClientConn.Connect error: unsupported minor version, less than 8: 0

**Comment by amitbet** [comment]
RealVnc server uses proprietary protocols which are more advanced versions
of rfb, since i don't have the spec for these protocols (they are not
public), they can't be supported...

You could switch to running one of the supported vnc servers like tightvnc,
or ask realvnc about the features you are looking for, since they have
additional complementary features in their payed version, and i think one
of them is session recording or video rec.
