### ISSUE TITLE
Mouse and keyboards events recording

### ISSUE THREAD

**Issue by MarkLTZ** [amitbet/vncproxy#17]
Hello!

I read vncproxy is able to record VNC session. Is this recorded video file such as MP4 or similar?

If not it could be nice to add this feature. and I think it is very nice to add also the feature to record  mouse and keyboard events as flat file "human readable" (or that can be parsed from 3rd party tools).

My opinion is that this feature is really useful for smart-working solutions. In this way, IT admins are able to provide a tool to employees or consultants for accessing to internal servers by VPN and at the same time record everything they do for security reasons. This is a MUST for forensic analysis

Regards,
Mark

**Comment by amitbet** [comment]
Vncproxy is able to record the VNC sessions, it uses RFB files which hold
the original stream, so there is no transcoding.
The vncproxy code doesn't perform full image construction as it is built
not to manage the pixel & palette data at all, other than dumping these
into the output file - this makes it lightweight and low cpu.
I do have a project called vnc2video which encodes the vnc stream into an
mp4 file, it reconstructs the actual screen from pixel data and sends these
images into ffmpeg to be encoded, but this usually requires a very high CPU
load since the encoding process is rather demanding (modern encodings like
h264 will eat up a ton of cpu even with the simplest profiles)

information about keyboard and mouse events is understood by the vncproxy
mechanism so such events can be saved to a human readable file with a
smallish coding effort (feel free to have a go at it).

**Comment by MarkLTZ** [comment]
Thanks a lot @amitbet for your explanation.
